import { Injectable, Logger } from '@nestjs/common';
import { DbService } from '../../db/db.service';
import { OpenAiChatService } from '../integrations/openai/openai-chat.service';
import { GmailApiService } from '../integrations/google/gmail-api.service';
import { CalendarApiService } from '../integrations/google/calendar-api.service';
import { HubspotApiService } from '../integrations/hubspot/hubspot-api.service';
import { InstructionsService, InstructionRow } from './instructions.service';

export type TriggerEvent = {
  type:
    | 'gmail_received'
    | 'gmail_sent'
    | 'calendar_event_created'
    | 'calendar_event_updated'
    | 'calendar_event_deleted'
    | 'hubspot_contact_created'
    | 'hubspot_contact_updated'
    | 'hubspot_contact_deleted'
    | 'hubspot_note_created'
    | 'hubspot_note_deleted';
  summary: string;
  data: Record<string, unknown>;
};

type ActionPlan = {
  shouldAct: boolean;
  matchingInstructionId: number | null;
  matchingInstructionText: string | null;
  actions: Array<{
    tool: string;
    description: string;
    params: Record<string, unknown>;
  }>;
  reasoning: string;
};

@Injectable()
export class InstructionExecutorService {
  private readonly logger = new Logger(InstructionExecutorService.name);

  constructor(
    private readonly dbService: DbService,
    private readonly llm: OpenAiChatService,
    private readonly instructionsService: InstructionsService,
    private readonly gmailApi: GmailApiService,
    private readonly calendarApi: CalendarApiService,
    private readonly hubspotApi: HubspotApiService,
  ) {}

  /**
   * Process a trigger event against user's active instructions.
   * Uses LLM to determine if any instruction applies and what action to take.
   */
  async processTrigger(
    userId: number,
    trigger: TriggerEvent,
    instructions: InstructionRow[],
  ): Promise<void> {
    if (instructions.length === 0) return;

    // Safety: Check for self-loop (agent's own emails)
    if (this.isSelfGeneratedTrigger(trigger)) {
      this.logger.debug(`[InstructionExecutor] Skipping self-generated trigger: ${trigger.type}`);
      return;
    }

    // Safety: Check idempotency - have we already processed this exact trigger?
    const alreadyProcessed = await this.instructionsService.isTriggerProcessed(
      userId,
      trigger.type,
      trigger.summary,
    );
    if (alreadyProcessed) {
      this.logger.debug(
        `[InstructionExecutor] Skipping already-processed trigger: ${trigger.type} - ${trigger.summary}`,
      );
      return;
    }

    // Check rate limit
    const rateLimit = await this.instructionsService.checkRateLimit(userId);
    if (!rateLimit.allowed) {
      this.logger.warn(
        `[InstructionExecutor] User ${userId} hit rate limit (${rateLimit.remaining} remaining)`,
      );
      return;
    }

    // Ask LLM to plan actions
    const plan = await this.planActions(userId, trigger, instructions);

    if (!plan.shouldAct) {
      this.logger.debug(`[InstructionExecutor] No action needed for trigger: ${trigger.type}`);
      return;
    }

    this.logger.log(
      `[InstructionExecutor] Executing ${plan.actions.length} action(s) for trigger: ${trigger.type}`,
    );

    // Execute the planned actions
    for (const action of plan.actions) {
      // Log the action as "running"
      const actionLogId = await this.instructionsService.logProactiveAction({
        userId,
        instructionId: plan.matchingInstructionId,
        instructionText: plan.matchingInstructionText ?? '',
        triggerType: trigger.type,
        triggerSummary: trigger.summary,
        triggerData: trigger.data,
        actionTaken: `${action.tool}: ${action.description}`,
        status: 'running',
      });

      try {
        const result = await this.executeAction(userId, action);

        // Update log to completed
        await this.instructionsService.updateProactiveAction(actionLogId, {
          status: 'completed',
          actionResult: result,
        });

        // Increment rate limit counter
        await this.instructionsService.incrementRateLimit(userId);
      } catch (err) {
        this.logger.error(
          `[InstructionExecutor] Action failed: ${err instanceof Error ? err.message : String(err)}`,
        );

        // Update log to failed
        await this.instructionsService.updateProactiveAction(actionLogId, {
          status: 'failed',
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }
  }

  /**
   * Check if this trigger was generated by the agent itself (to prevent loops)
   */
  private isSelfGeneratedTrigger(trigger: TriggerEvent): boolean {
    if (trigger.type === 'gmail_received') {
      const data = trigger.data;

      // Check if this is flagged as sent by us (from the worker)
      if (data.isSent === true) {
        return true;
      }

      // Check for markers that indicate automated emails
      const snippet = safeString(data.snippet).toLowerCase();
      const subject = safeString(data.subject).toLowerCase();

      if (snippet.includes('[sent by ai assistant]') || subject.includes('[automated]')) {
        return true;
      }
    }

    return false;
  }

  /**
   * Use LLM to determine what actions (if any) should be taken
   */
  private async planActions(
    _userId: number,
    trigger: TriggerEvent,
    instructions: InstructionRow[],
  ): Promise<ActionPlan> {
    if (!this.llm.isConfigured()) {
      return {
        shouldAct: false,
        matchingInstructionId: null,
        matchingInstructionText: null,
        actions: [],
        reasoning: 'LLM not configured',
      };
    }

    const instructionsList = instructions
      .map((inst, i) => `${i + 1}. [ID:${inst.id}] "${inst.instruction}"`)
      .join('\n');

    const triggerDescription = `
Type: ${trigger.type}
Summary: ${trigger.summary}
Details: ${JSON.stringify(trigger.data, null, 2)}
    `.trim();

    const systemPrompt = `You are evaluating whether any ongoing instructions apply to a trigger event.

TRIGGER EVENT:
${triggerDescription}

USER'S ACTIVE INSTRUCTIONS:
${instructionsList}

AVAILABLE TOOLS:

**Gmail Tools:**
- gmail_send_email: Send a new email (params: to, subject, bodyText, cc?, bcc?)
- gmail_reply: Reply to an email thread (params: threadId, bodyText)
- gmail_search: Search for emails (params: query, maxResults?) - returns list of emails matching query
- gmail_get_thread: Get full thread content (params: threadId) - returns all messages in a thread

**Calendar Tools:**
- calendar_create_event: Create a calendar event (params: summary, startIso, endIso, description?, attendees?)
- calendar_update_event: Update a calendar event (params: eventId, summary?, startIso?, endIso?, description?)
- calendar_delete_event: Delete/cancel a calendar event (params: eventId)
- calendar_find_events: Search for events (params: query?, attendeeEmail?, timeMinIso?, timeMaxIso?, maxResults?)

**HubSpot Tools:**
- hubspot_create_contact: Create a new contact (params: email, firstName?, lastName?)
- hubspot_update_contact: Update contact fields (params: contactId, email?, firstName?, lastName?, company?, phone?)
- hubspot_delete_contact: Delete a contact (params: contactId)
- hubspot_get_contact: Get contact details (params: contactId? or email?)
- hubspot_find_contact: Search for contacts (params: query, maxResults?)
- hubspot_find_or_create_contact: Find or create contact + optional note (params: email, firstName?, lastName?, noteBody?)
- hubspot_create_note: Add a note to a contact (params: contactId, body)
- hubspot_delete_note: Delete a note (params: noteId)

EXTRACTING CONTACT INFO FROM EMAILS:
For gmail_received triggers, the "sender" object contains parsed info:
- sender.email: The sender's email address (always available)
- sender.firstName: First name (only if sender's email client included it, e.g., "John Smith <email>")
- sender.lastName: Last name (only if available in email header)
- sender.name: Full name (only if available)

IMPORTANT: firstName/lastName will be null if the email was sent as just "email@example.com" 
without a display name. This is fine - create the contact with just the email address.
Do NOT invent or guess names.

Return ONLY valid JSON:
{
  "shouldAct": boolean,
  "matchingInstructionIndex": number | null,  // 1-based index
  "reasoning": string,
  "actions": [
    {
      "tool": string,
      "description": string,  // Human-readable description of what we're doing
      "params": { ... }  // Tool-specific parameters
    }
  ]
}

IMPORTANT RULES:
- Only act if an instruction CLEARLY applies to this trigger
- Don't act on automated/system emails (noreply@, notifications, newsletters, marketing)
- Use hubspot_find_or_create_contact when creating contacts from emails - it handles the "check if exists" logic
- Use calendar_find_events when you need to look up meeting times
- Use gmail_get_thread if you need the full email content beyond the snippet
- Be conservative - when in doubt, don't act
- If replying to email, keep it professional and brief
- Consider the INTENT behind the instruction, not just literal matching
- For note bodies, include relevant context like email subject and a brief snippet
- NEVER act on emails that appear to be sent by an AI/automated system

EXAMPLES:

Instruction: "When someone emails me that's not in HubSpot, create a contact"
Trigger: gmail_received with sender.email="john@newclient.com", sender.firstName="John"
-> Use hubspot_find_or_create_contact with email="john@newclient.com", firstName="John"

Instruction: "When someone asks about our next meeting, look it up and respond"
Trigger: gmail_received asking "When is our next call?"
-> First use calendar_find_events with attendeeEmail=sender.email to find meetings
-> Then use gmail_reply to respond with the meeting details

Instruction: "When I add an event, email attendees about the meeting"
Trigger: calendar_event_created with attendees ["sara@x.com"], summary="Q1 Review"
-> Use gmail_send_email to each attendee about the meeting`;

    try {
      const raw = await this.llm.complete({
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: 'Analyze and plan actions.' },
        ],
        temperature: 0.0,
      });

      const parsed = safeJsonParse(raw);
      if (!isRecord(parsed)) {
        return {
          shouldAct: false,
          matchingInstructionId: null,
          matchingInstructionText: null,
          actions: [],
          reasoning: 'Failed to parse LLM response',
        };
      }

      const shouldAct = parsed.shouldAct === true;
      const matchingIndex =
        typeof parsed.matchingInstructionIndex === 'number'
          ? parsed.matchingInstructionIndex
          : null;

      const matchingInstruction =
        matchingIndex !== null && matchingIndex >= 1 && matchingIndex <= instructions.length
          ? instructions[matchingIndex - 1]
          : null;

      const actions = Array.isArray(parsed.actions)
        ? parsed.actions
            .filter((a): a is Record<string, unknown> => isRecord(a))
            .map((a) => ({
              tool: typeof a.tool === 'string' ? a.tool : '',
              description: typeof a.description === 'string' ? a.description : '',
              params: isRecord(a.params) ? a.params : {},
            }))
            .filter((a) => a.tool)
        : [];

      const reasoning = typeof parsed.reasoning === 'string' ? parsed.reasoning : '';

      return {
        shouldAct,
        matchingInstructionId: matchingInstruction?.id ?? null,
        matchingInstructionText: matchingInstruction?.instruction ?? null,
        actions,
        reasoning,
      };
    } catch (err) {
      this.logger.error(
        `[InstructionExecutor] planActions failed: ${err instanceof Error ? err.message : String(err)}`,
      );
      return {
        shouldAct: false,
        matchingInstructionId: null,
        matchingInstructionText: null,
        actions: [],
        reasoning: `Error: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  }

  /**
   * Execute a single action
   */
  private async executeAction(
    userId: number,
    action: { tool: string; description: string; params: Record<string, unknown> },
  ): Promise<Record<string, unknown>> {
    const { tool, params } = action;

    switch (tool) {
      // =========================================================================
      // GMAIL TOOLS
      // =========================================================================
      case 'gmail_send_email': {
        const result = await this.gmailApi.sendEmail(userId, {
          to: safeString(params.to),
          subject: safeString(params.subject),
          bodyText: safeString(params.bodyText),
          cc: safeStringOrUndefined(params.cc),
          bcc: safeStringOrUndefined(params.bcc),
        });
        return { success: true, result };
      }

      case 'gmail_reply': {
        const threadId = safeString(params.threadId);
        const bodyText = safeString(params.bodyText);

        // Get thread info for proper reply
        const messages = await this.gmailApi.getThreadMessages(userId, threadId);
        const lastMessage = messages[messages.length - 1];

        const result = await this.gmailApi.sendEmail(userId, {
          to: lastMessage?.headers.from ?? '',
          subject: lastMessage?.headers.subject
            ? `Re: ${lastMessage.headers.subject.replace(/^Re:\s*/i, '')}`
            : 'Re:',
          bodyText,
          threadId,
          inReplyToMessageId: lastMessage?.headers.messageId,
        });
        return { success: true, result };
      }

      case 'gmail_search': {
        const query = safeString(params.query);
        const maxResults = safeNumber(params.maxResults, 10);
        const results = await this.gmailApi.listMessageIds(userId, { q: query, maxResults });
        return { success: true, messageIds: results };
      }

      case 'gmail_get_thread': {
        const threadId = safeString(params.threadId);
        const messages = await this.gmailApi.getThreadMessages(userId, threadId);
        return { success: true, messages };
      }

      // =========================================================================
      // CALENDAR TOOLS
      // =========================================================================
      case 'calendar_create_event': {
        const attendeesRaw = params.attendees;
        const attendees = Array.isArray(attendeesRaw)
          ? attendeesRaw
              .map((a) => {
                if (typeof a === 'string') return { email: a };
                if (isRecord(a)) {
                  return {
                    email: safeString(a.email),
                    displayName: safeStringOrUndefined(a.displayName),
                  };
                }
                return null;
              })
              .filter((a): a is { email: string; displayName?: string } => a !== null && !!a.email)
          : undefined;

        const result = await this.calendarApi.createEvent(userId, {
          summary: safeString(params.summary),
          startIso: safeString(params.startIso),
          endIso: safeString(params.endIso),
          description: safeStringOrUndefined(params.description),
          attendees,
        });
        return { success: true, eventId: result.id };
      }

      case 'calendar_update_event': {
        const result = await this.calendarApi.updateEvent(userId, {
          eventId: safeString(params.eventId),
          summary: safeStringOrUndefined(params.summary),
          startIso: safeStringOrUndefined(params.startIso),
          endIso: safeStringOrUndefined(params.endIso),
          description: safeStringOrUndefined(params.description),
        });
        return { success: true, eventId: result.id };
      }

      case 'calendar_delete_event': {
        const eventId = safeString(params.eventId);
        await this.calendarApi.deleteEvent(userId, eventId);
        return { success: true, eventId, deleted: true };
      }

      case 'calendar_find_events': {
        const query = safeStringOrUndefined(params.query);
        const attendeeEmail = safeStringOrUndefined(params.attendeeEmail);
        const timeMinIso = safeStringOrUndefined(params.timeMinIso) ?? new Date().toISOString();
        const timeMaxIso =
          safeStringOrUndefined(params.timeMaxIso) ??
          new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();
        const maxResults = safeNumber(params.maxResults, 10);

        const events = await this.calendarApi.findEvents(userId, {
          query,
          attendeeEmail,
          timeMinIso,
          timeMaxIso,
          maxResults,
        });
        return { success: true, events };
      }

      // =========================================================================
      // HUBSPOT TOOLS
      // =========================================================================
      case 'hubspot_create_contact': {
        const result = await this.hubspotApi.createContact(userId, {
          email: safeString(params.email),
          firstName: safeStringOrUndefined(params.firstName),
          lastName: safeStringOrUndefined(params.lastName),
        });
        return { success: true, contactId: result.id };
      }

      case 'hubspot_update_contact': {
        const contactId = safeString(params.contactId);
        const result = await this.hubspotApi.updateContact(userId, contactId, {
          email: safeStringOrUndefined(params.email),
          firstName: safeStringOrUndefined(params.firstName),
          lastName: safeStringOrUndefined(params.lastName),
          company: safeStringOrUndefined(params.company),
          phone: safeStringOrUndefined(params.phone),
        });
        return { success: true, contactId: result.id };
      }

      case 'hubspot_delete_contact': {
        const contactId = safeString(params.contactId);
        await this.hubspotApi.deleteContact(userId, contactId);
        return { success: true, contactId, deleted: true };
      }

      case 'hubspot_get_contact': {
        const contactId = safeStringOrUndefined(params.contactId);
        const email = safeStringOrUndefined(params.email);

        if (contactId) {
          const contact = await this.hubspotApi.getContact(userId, contactId);
          return { success: true, contact };
        } else if (email) {
          const contacts = await this.hubspotApi.searchContacts(userId, email, 1);
          const contact = contacts.find((c) => c.email?.toLowerCase() === email.toLowerCase());
          return { success: true, contact: contact ?? null, found: !!contact };
        } else {
          throw new Error('Either contactId or email is required');
        }
      }

      case 'hubspot_find_contact': {
        const query = safeString(params.query);
        const maxResults = safeNumber(params.maxResults, 10);
        const contacts = await this.hubspotApi.searchContacts(userId, query, maxResults);
        return { success: true, contacts };
      }

      case 'hubspot_find_or_create_contact': {
        const email = safeString(params.email);
        const firstName = safeStringOrUndefined(params.firstName);
        const lastName = safeStringOrUndefined(params.lastName);
        const noteBody = safeStringOrUndefined(params.noteBody);

        if (!email) {
          throw new Error('Email is required for hubspot_find_or_create_contact');
        }

        // Use the existing findOrCreateContactByEmail method
        const result = await this.hubspotApi.findOrCreateContactByEmail(userId, {
          email,
          firstName,
          lastName,
        });

        // Add note if requested
        let noteId: string | null = null;
        if (noteBody && result.id) {
          const noteResult = await this.hubspotApi.createNoteOnContact(userId, {
            contactId: result.id,
            body: noteBody,
          });
          noteId = noteResult.noteId;
        }

        return {
          success: true,
          contactId: result.id,
          wasCreated: result.created,
          alreadyExisted: !result.created,
          noteId,
        };
      }

      case 'hubspot_create_note': {
        const result = await this.hubspotApi.createNoteOnContact(userId, {
          contactId: safeString(params.contactId),
          body: safeString(params.body),
        });
        return { success: true, noteId: result.noteId };
      }

      case 'hubspot_delete_note': {
        const noteId = safeString(params.noteId);
        await this.hubspotApi.deleteNote(userId, noteId);
        return { success: true, noteId, deleted: true };
      }

      default:
        throw new Error(`Unknown tool: ${tool}`);
    }
  }
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

function safeJsonParse(text: string): unknown {
  if (!text) return null;
  try {
    const cleaned = text
      .replace(/```json\s*/g, '')
      .replace(/```\s*/g, '')
      .trim();
    return JSON.parse(cleaned);
  } catch {
    return null;
  }
}

function isRecord(x: unknown): x is Record<string, unknown> {
  return typeof x === 'object' && x !== null && !Array.isArray(x);
}

function safeString(value: unknown): string {
  if (typeof value === 'string') return value;
  if (value === null || value === undefined) return '';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return '';
}

function safeStringOrUndefined(value: unknown): string | undefined {
  if (typeof value === 'string') return value;
  if (value === null || value === undefined) return undefined;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return undefined;
}

function safeNumber(value: unknown, defaultValue: number): number {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string') {
    const parsed = parseInt(value, 10);
    if (Number.isFinite(parsed)) return parsed;
  }
  return defaultValue;
}
